### ISSUE TITLE
Update to newer k3d version

### ISSUE THREAD

**Issue by mowies** [AbsaOSS/k3d-action#45]
k3d is already at [version v5.4.6](https://github.com/k3d-io/k3d/releases/tag/v5.4.6).

It would be great to update this action with it.

**Comment by kuritka** [comment]
Hi @mowies , thx for comment. Starting from k3d-action v2.1.0 users can explicitly set k3d version via `k3d-version` input e.g. `k3d-version: v5.4.6` otherwise k3d uses default version (currently `v5.4.1`). However we will set the default to the latest k3d soon.

**Comment by mowies** [comment]
I know that that's possible, still it would be great to have this actual default to the latest version as you said :)
